### ISSUE TITLE
Privacy Manifest Update is needed?

### ISSUE THREAD

**Issue by ge-mehrdad** [rinov/YoutubeKit#100]
Hey @rinov 

Since we're getting close to May 2024 deadline for Apple's new guidelines on including Privacy Manifest for frameworks, was wondering if we need it for this framework?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by rinov** [comment]
Yes, these measures are necessary even for 3rd party SDKs, so we are currently working on implementing them.
We plan to release a new version by the end of next week.

**Comment by rinov** [comment]
However, as of the end of April, only the following general SDKs are subject to this requirement, and it is not yet mandatory for other SDKs.

https://developer.apple.com/jp/support/third-party-SDK-requirements/
