### ISSUE TITLE
Start Playing automaticly

### ISSUE THREAD

**Issue by TMXJojo** [rinov/YoutubeKit#11]
Hey, again. 

After testing for while, I found this bug. The Player starts playing automatically (even without setting autoplay) when you push a Controller, and then pop back . 

Here is an example: 
![ezgif-2-bf616a5fa6](https://user-images.githubusercontent.com/40988575/42627724-27f1ad32-85ce-11e8-9acf-6fc34762a261.gif)

I only do:
```swift
        // Create a new player
        player = YTSwiftyPlayer(
            frame: YTContainer.bounds,
            playerVars: [ .videoID(loadedID), .showInfo(false), .showRelatedVideo(false)])
        
        // Set it
        ...
        // Set delegate for detect callback information from the player
        player.delegate = self
        // Load video player
        player.loadPlayer()
```

**Comment by rinov** [comment]
Dup https://github.com/rinov/YoutubeKit/issues/6
