### ISSUE TITLE
this video is not available

### ISSUE THREAD

**Issue by appsird** [rinov/YoutubeKit#18]
Thanks for the update player.

If you bringup the following URL in your browser, it will play fine.

https://youtu.be/BJq4d1-lHq8

If I set the following in the Example app ViewController using the above videoID:

        player = YTSwiftyPlayer(
            frame: CGRect(x: 0, y: 0, width: 640, height: 480),
            playerVars: [.playsInline(true), .videoID("BJq4d1-lHq8"), .loopVideo(false), .showRelatedVideo(false)])

I receive the error "this videos is not available".

Though, using the swift player here:

https://github.com/gilesvangruisen/Swift-YouTube-Player

This video plays when passing in the full URL https://youtu.be/BJq4d1-lHq8. Is there a means to pass in a full URL for video playback using YoutubeKit?

I would prefer your player, as it appears more memory efficient.

Thanks.

**Comment by appsird** [comment]
Thank you for your prompt response. Let's work into this issue in steps.

First, I downloaded your git project and had several issues with code signing issues which I was able to resolve. Specifically I needed to set 'Automatically manage signing' for all frameworks to compile, including I ran the Youtubekit-Example and the video plays on my iphone7 and iphone8 simulator. However while the video is playing I press the expand arrows in the bottom right of the screen, and I receive numerous auto layout errors in my console. 

<img width="407" alt="untitled" src="https://user-images.githubusercontent.com/8471833/42734412-611d2c72-87f8-11e8-904b-d4fab7c83e0e.png">


player(_:didUpdateCurrentTime:):18.2633779242716
player(_:didUpdateCurrentTime:):18.7696120347732
player(_:didUpdateCurrentTime:):19.2762538737349
player(_:didUpdateCurrentTime:):19.7782703887955
player(_:didUpdateCurrentTime:):20.2820842693929
2018-07-15 06:02:43.563606-0700 utube[1746:515094] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1c0287df0 'UISV-canvas-connection' UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'.leading == _UILayoutSpacer:0x1c01cca80'UISV-ordering-spanner'.leading   (active)>",
    "<NSLayoutConstraint:0x1c0287e40 'UISV-canvas-connection' UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'.trailing == _UILayoutSpacer:0x1c01cca80'UISV-ordering-spanner'.trailing   (active)>",
    "<NSLayoutConstraint:0x1c02877b0 'UIView-Encapsulated-Layout-Width' UIStackView:0x1029199d0.width == 0   (active)>",
    "<NSLayoutConstraint:0x1c0287a80 'UIView-leftMargin-guide-constraint' H:|-(12)-[UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':UIStackView:0x1029199d0 )>",
    "<NSLayoutConstraint:0x1c0287b20 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide']-(12)-|(LTR)   (active, names: '|':UIStackView:0x1029199d0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1c0287e40 'UISV-canvas-connection' UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'.trailing == _UILayoutSpacer:0x1c01cca80'UISV-ordering-spanner'.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-07-15 06:02:43.565533-0700 utube[1746:515094] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1c0288160 'UISV-canvas-connection' UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'.top == _UILayoutSpacer:0x1c01ce010'UISV-alignment-spanner'.top   (active)>",
    "<NSLayoutConstraint:0x1c02881b0 'UISV-canvas-connection' UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'.bottom == _UILayoutSpacer:0x1c01ce010'UISV-alignment-spanner'.bottom   (active)>",
    "<NSLayoutConstraint:0x1c0287ad0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide']-(12)-|   (active, names: '|':UIStackView:0x1029199d0 )>",
    "<NSLayoutConstraint:0x1c0287800 'UIView-Encapsulated-Layout-Height' UIStackView:0x1029199d0.height == 0   (active)>",
    "<NSLayoutConstraint:0x1c0287a30 'UIView-topMargin-guide-constraint' V:|-(12)-[UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x1029199d0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1c02881b0 'UISV-canvas-connection' UILayoutGuide:0x1c01b6a40'UIViewLayoutMarginsGuide'.bottom == _UILayoutSpacer:0x1c01ce010'UISV-alignment-spanner'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
player(_:didUpdateCurrentTime:):20.7826937327764
player(_:didUpdateCurrentTime:):21.282467166837
2018-07-15 06:02:44.310092-0700 utube[1746:515372] [] <<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_Presence (client: utube)
player(_:didChangeQuality:):hd720
player(_:didUpdateCurrentTime:):21.7830786603163
player(_:didUpdateCurrentTime:):22.2842714117924
player(_:didChangeQuality:):hd720

**Comment by phamthanhluan** [comment]
![screen shot 2018-08-04 at 4 32 02 pm](https://user-images.githubusercontent.com/12554836/43674868-46bc1bb0-9804-11e8-9b7e-8a3a892b9f16.png)
I also get message this video is unavailable.

**Comment by rinov** [comment]
@appsird Hi, Sorry for my late reply.
Thank you for your clear explanation but i'm not sure why the video cannot play.
I'm release a new version `0.2.4`, so please try it on `0.2.4`.  It might have been fixed at now.
