### ISSUE TITLE
Is there any way to stop showing "More Videos" in the player

### ISSUE THREAD

**Issue by talis00051** [rinov/YoutubeKit#25]
As described on the title.
This library fits most of my product requirements which is amazing, except the "More Viedo" bar in the video player.
Is there any where to solve it?
Thank you!

**Comment by lehelmedves** [comment]
Hi @rinov ,

I have also experienced this, at the end of the video the related videos are shown for instance for this video: swWXElebrLI. Can this be avoided?

**Comment by talis00051** [comment]
Sorry for late response. Yes it is the related videos and I found out the solution.
`youtubeView = YTSwiftyPlayer(frame: view.frame, playerVars: [VideoEmbedParameter.videoID(String(url.suffix(11))), **VideoEmbedParameter.showRelatedVideo(false)**, VideoEmbedParameter.showModestbranding(false)])`

**Comment by lehelmedves** [comment]
Hey @talis00051 ,

I am already using the showRelatedVideo, but with this particular video I mentioned it doesn't help, at the end of the video a list of related videos will still be listed.

**Comment by talis00051** [comment]
This library is created base on YouTube iFrame Player API. And YouTube iFrame Player API has announced that related video has been changed since September 25, 2018. Below is the capture from [https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018](url)

**The behavior for the rel parameter is changing on or after September 25, 2018. The effect of the change is that you will not be able to disable related videos. However, you will have the option of specifying that the related videos shown in the player should be from the same channel as the video that was just played.

To be more specific:
Prior to the change, if the parameter's value is set to 0, then the player does not show related videos.
After the change, if the rel parameter is set to 0, the player will show related videos that are from the same channel as the video that was just played.**

Clearly stated that related videos will always be shown from now on, and nothing we can do with this.

**Comment by lehelmedves** [comment]
I see, thank you so much for the quick answer @talis00051 , if it cannot be done, it cannot be done, it really depends on Youtube this time.

I have one more question: I can set the start and end times through the API, however, these are not taken into account in case of looping. Is this a bug in the library or does this also depend on Youtube's API?

**Comment by shyamal** [comment]
Yes we can set star and end time. 

Issue depend on youtube API.

**Comment by wdcurry** [comment]
> I see, thank you so much for the quick answer @talis00051 , if it cannot be done, it cannot be done, it really depends on Youtube this time.
> 
> I have one more question: I can set the start and end times through the API, however, these are not taken into account in case of looping. Is this a bug in the library or does this also depend on Youtube's API?

Indeed, the loop issue seems to relate to the library itself. I don't recall where i read that though, sorry.
