### ISSUE TITLE
Exit full screen event at youtube player

### ISSUE THREAD

**Issue by felixchang123** [rinov/YoutubeKit#26]
How can I get the exit full screen event ?
When I click exit button at youtube player, I got the error:
2018-08-01 18:02:48.031222+0800 YoutubeKit_Example[13986:3656284] -[AVPlayerViewController exitFullScreenAnimated:completionHandler:] failed with error View needs to be loaded before you can call -[AVPlayerViewController (0x10484ec00) exitFullScreenAnimated:completionHandler:]!

**Comment by lehelmedves** [comment]
Hello!

I also have a question regarding FullScreen mode: is there any way of forcing fullscreen mode manually through an API call?

**Comment by oguzparlak** [comment]
Is there any solution to this problem ?

**Comment by tcordoba** [comment]
I found a solution that is working for me. 

```
private var isFullScreen: Bool = false

deinit {
        NotificationCenter.default.removeObserver(UIWindow.didBecomeKeyNotification)
    }

override func viewDidLoad() {
        super.viewDidLoad()
    
        NotificationCenter.default.addObserver(
            forName: UIWindow.didBecomeKeyNotification,
            object: self.view.window,
            queue: nil
        ) { notification in
            if self.isFullScreen {
                // Is leaving full screen!, in my case I pop out my view controller
                self.navigationController?.popViewController(animated: true)
            }
            self.isFullScreen = true
        }
    }
```
