### ISSUE TITLE
IPad doesn't load in default video player, but in browser. Works fine on IPhone.

### ISSUE THREAD

**Issue by TonyNikolov** [rinov/YoutubeKit#27]
This can easily be recreated, with a new project and copy pasting the code from the example. I initially tested it on the Example project and it loaded using the default video player on IPad and IPhone. There appears to be something different about the Example Project and i cant figure it out, could anyone help out??
![](https://i.imgur.com/D8P2GO3.jpg)

**Comment by RebeccaCurties** [comment]
Why does it open only on iphone and not in ipad?

**Comment by ericlsh** [comment]
After changing WKWebviewConfiguration.allowsInlineMediaPlayback = false, ipad could run default video player in fullscreen. Not sure for inline play.
