### ISSUE TITLE
swift 4.1 init

### ISSUE THREAD

**Issue by alfasolutions** [rinov/YoutubeKit#4]
A compiler error after update to swift 4.1

'self' used in method call 'defaultConfiguration' before 'super.init' call !!!

    public init(frame: CGRect = .zero, playerVars: [String: AnyObject]) {
        super.init(frame: frame, configuration: defaultConfiguration())
        
        commonInit()
        self.playerVars = playerVars
    }
    
    public init(frame: CGRect = .zero, playerVars: [VideoEmbedParameter] = []) {
        super.init(frame: frame, configuration: defaultConfiguration())
        
        commonInit()
        guard !playerVars.isEmpty else { return }
        var params: [String: AnyObject] = [:]
        playerVars.forEach {
            let property = $0.property
            params[property.key] = property.value
        }
        self.playerVars = params
    }

**Comment by mzeeshanid** [comment]
I am also facing the same probelm :(

**Comment by rinov** [comment]
Hi there, Thank you for your report an issue.
Sorry, This library is still not convertible with Swift 4.1 because i mainly use Swift 4 on my work, but i wanna fix it in near the future, or i'm very happy if you submit a pull request :).

**Comment by rinov** [comment]
I've just fixed this issue at YoutubeKit (v0.2.0), 
Thank you.
