### ISSUE TITLE
Trouble accessing custom error for reject()

### ISSUE THREAD

**Issue by wdcurry** [rinov/YoutubeKit#46]
I have a separate public error swift file to help organize my efforts, located in the sample demo. I am drawing a blank as to why i cannot access it from within the reject() location within the
`Return Promise<VideoListRequest.Response?>(in: .background, { resolve, reject, _ in`
block.  Unless i have it physically located in the swift file itself, it is unknown, despite (strangely) being able to "Jump to Definition" ..  I finally just left it there and moved on, but left a //TODO: in my code.

Anyone else see this, or know what is wrong? The public enum works perfectly from within the code file in question.

**Comment by rinov** [comment]
If you still need support, please attach more detailed code.
Thank you.
