### ISSUE TITLE
new warnings in Xcode 10.2

### ISSUE THREAD

**Issue by appsird** [rinov/YoutubeKit#48]
This release arrived today and elicits some new warnings per below

<img width="1407" alt="Screen Shot 2019-03-25 at 3 57 52 PM" src="https://user-images.githubusercontent.com/8471833/54959589-d7359a80-4f16-11e9-8bdc-03623291d64e.png">

**Comment by rinov** [comment]
I've fixed these warnings in 0.4.0.
Thank you :)
