### ISSUE TITLE
Details are too small

### ISSUE THREAD

**Issue by mrugeshtank** [rinov/YoutubeKit#52]
Can you please help me to solve this issue?
"Watch later", "Share" and uploader account info is too much small, also Play button of Youtube is also small.

Attaching screenshot if iPhone X simulator iOS 12.1

![Simulator Screen Shot - iPhone X - 2019-06-03 at 19 32 44](https://user-images.githubusercontent.com/11042449/58808635-07e13100-8638-11e9-805b-a3794643e803.png)

**Comment by hlwanhoj** [comment]
It may due to the `viewport` meta not set in the html template, please try adding 
```
<meta name="viewport" content="initial-scale = 1, user-scalable = no">
```
to the html template

**Comment by wassupb** [comment]
Hi H, 
Can you please tell me what html template are you referring to?  The location to put the meta tag?  Thank you so much.

**Comment by hlwanhoj** [comment]
The framework does not provide a way to configure the viewport, thus you need to fork and modify it. There is a file named `player.html` in this pod which is the place the IFrame youtube player lies in. Insert a `meta` for `viewport` in the `head` of that html and the player will reflect the changes
