### ISSUE TITLE
auto play not working

### ISSUE THREAD

**Issue by xuuz** [rinov/YoutubeKit#6]
Hi @rinov 
Thanks for answesome library.
I just try with auto play when load video, but it's seem not work, the code is your example:

```
player = YTSwiftyPlayer(
            frame: CGRect(x: 0, y: 0, width: 640, height: 480),
            playerVars: [.autoplay(true), .playsInline(true), .videoID("NPiYTw8WkyU")])

```
Could you please detect why? Thanks a million!

**Comment by kirimaru89** [comment]
as I read from here: https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations,
it is not allowed to autoplay video in mobile :(
"Warning: To prevent unsolicited downloads over cellular networks at the user’s expense, embedded media cannot be played automatically in Safari on iOS — the user always initiates playback."

**Comment by rinov** [comment]
↑right, it doesn't work due to this reason.
So, If you want use auto playback function,  use `autoplay` property instead.
This will work despite of mobile environment.

Thank you.

https://github.com/rinov/YoutubeKit/blob/master/YoutubeKit/Player/YTSwiftyPlayer.swift#L20

**Comment by akisute** [comment]
> Set mediaTypesRequiringUserActionForPlayback to a value that excludes video, e.g. .audio or []. If you don’t do this, the user will need to tap on the play button in the video to start it. Since we do not declare the control attribute on the video element, the play button is not visible and the video is basically unplayable.

https://www.thomasvisser.me/2018/06/26/wkwebview-media/

> mediaTypesRequiringUserActionForPlayback
> Determines which media types require a user gesture to begin playing.
> Use WKAudiovisualMediaTypeNone to indicate that no user gestures are required to begin playing media.

https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1851524-mediatypesrequiringuseractionfor
