### ISSUE TITLE
Swift Packages

### ISSUE THREAD

**Issue by amberreyn** [rinov/YoutubeKit#67]
Hope this finds you well. Good job with Youtubkit. I was wondering if you plan to make it work with Swift packages. I'd like to use this with my new project and trying not to use Cocoapods. Thanks!

**Comment by amberreyn** [comment]
Hi. Looks like you added the swift package. Thanks!  I'm getting compile issues on ActivityListRequest.swift and RequestableExtension.swift.

**Comment by amberreyn** [comment]
error is use of undeclared type 'Date'

maybe try adding import Foundation to those files

**Comment by mergesort** [comment]
I ran into the same thing for the record. Pretty sure all that's missing is `import Foundation`, but can't add that in a Swift package without forking the project since they're immutable.

**Comment by mergesort** [comment]
I fixed it locally by adding those imports, but realized that you can't actually use this package as is with SPM due to SPM's lack of support for resources, and filed a ticket for it here https://github.com/rinov/YoutubeKit/issues/69.

**Comment by rinov** [comment]
dup. https://github.com/rinov/YoutubeKit/issues/69
