### ISSUE TITLE
how to I embed YTSwiftyPlayer inside a UIView and make it honor the UIView's bounds?

### ISSUE THREAD

**Issue by vittalk** [rinov/YoutubeKit#70]
Hi, 
I have a question. How do I embed YTSwiftyPlayer(ie WKWebView) inside a UIView and make it honor the UIView's bounds? 
I have tried but it looks like the YTSwiftyPlayer ignores the bounds. Greatly appreciate any help.
Thanks Vittal
(email-dot-vittal-at-gmail-dot-com)

@IBOutlet weak var viewForYTPlayer: UIView!
player = YTSwiftyPlayer(
            frame: viewForYTPlayer.bounds,
                   playerVars: [
                       .playsInline(true),
                       .videoID("0GCW7VkojeQ"),
                       .loopVideo(true),
                       .showRelatedVideo(false)
                   ])
        viewForYTPlayer.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        self.viewForYTPlayer.addSubview(player)

**Comment by hlwanhoj** [comment]
You should set `autoresizingMask` on `player` to let it responds to superview's bounds changes

**Comment by che1404** [comment]
Hi @vittalk , I'm trying to do the same. Did you manage to do it?
