### ISSUE TITLE
when playsInline = 1 , the progress view and current video Time  is hidden 

### ISSUE THREAD

**Issue by qusai286x** [rinov/YoutubeKit#74]
videoPlayer = YTSwiftyPlayer(
            frame: frame,
            playerVars:  [
                           .playsInline(true),
                           .videoID(videoId)
                           
                       ])

**Comment by closerminds** [comment]
same problem, @qusai286x no news ?

**Comment by rinov** [comment]
The issue of the YouTube embedded player not showing the progress bar and current video time when in 'inline play' mode is due to YouTube's specifications. To resolve this, you may need to set playsInline to false for full-screen mode, or create a custom UI to display these elements yourself.
