### ISSUE TITLE
How detect event on close button over video player?

### ISSUE THREAD

**Issue by ErwinJonn** [rinov/YoutubeKit#83]
I want to know if is possible detect when the user tap over close button to close video player.

Actually, the state return is "paused", but I need difference between paused button and close button. To shot an action over parent ViewController.

Someone knows something about that?.

Thanks friends.

**Comment by rinov** [comment]
YouTube iFrame API does not provide a separate event for detecting the close button being tapped. 

As an alternative workaround, you can try implementing a custom close button on top of the player and handle the tap event of that button separately. However, this would require additional UI customization and may not seamlessly integrate with the YouTube player, so it may not be the ideal solution, or you can try detecting the timing of the dismissal, such as when the player is being dismissed, by utilizing the delegate method in the UIViewController.

Thank you.
