### ISSUE TITLE
Help Needed - How to optimize performance for frequent loading

### ISSUE THREAD

**Issue by MichaelJoo** [rinov/YoutubeKit#93]
I am currently creating an app that scrolls Youtube Videos like Tiktok. 

I am using TableView for horizontal scrolling. My code looks something like below and it works as expected, just that it doesn't seem to be enough. Each cell would have its own Youtube Video (which loads successfully due to this great library), but there is "accumulating" impact to the memory. 

What I mean is that, the more scrolling the user does, the higher memory needed, and eventually it affects the performance/scrolling, etc. 

So I tried to write a piece of code to **.clearVideo()** everytime, the video is out of visible area of the phone. But for some reason, it doesn't work and I am not able to look into **evaluatePlayerCommand** function. 

Could you please let me know how I can completely "remove" initially loaded Youtube Video, so it will not impact the memory performance? 

```
let visibleRows = activeExerciseTableView.indexPathsForVisibleRows
        
                if let visibleRows = visibleRows {
                    visibleRows.forEach { indexPath in
                        if let cell = activeExerciseTableView.cellForRow(at: indexPath) as? ActiveExerciseTableViewCell, activeExerciseTableView.bounds.contains(cell.frame) {
                        
                            for (index, setViewModel) in cellExercise.sets.enumerated() {
                                
                                if indexPath.row != index {
                                    setViewModel.shouldPlayVideo = false
                                    
                                    cell.ytVideoPlayer.clearVideo()

                                }
                                
                                else if indexPath.row == index {
                                    setViewModel.shouldPlayVideo = true
                                    
                                    cell.ytVideoPlayer.playVideo()
                                    
                                }
                            
                            }
```

**Comment by rinov** [comment]
The YTSwiftyPlayer internally uses WKWebView and operates the video buffering and loading through the JavaScript IFrame API. Therefore, in addition to hiding the UI when it goes off-screen in Swift, you also need to purge the unnecessary video information from memory.

Here's an example:

```swift
override func prepareForReuse() {
    super.prepareForReuse()
    ytVideoPlayer.clearVideo()
    ytVideoPlayer.removeFromSuperview()  // or .isHidden = true
    ytVideoPlayer = nil
}
```

And in your player.html

```html
player.removeEventListener(event:String, listener:String) // If already added any listeners
player.destroy()
```

**Comment by MichaelJoo** [comment]
Thanks Rinov, 

    // MARK: - Lifecycle
    override func prepareForReuse() {
        super.prepareForReuse()
        guard let setViewModel = setViewModel else {
            return
        }
        setViewModel.delegate = nil
        ytVideoPlayer.clearVideo()   // Clears the video.
        ytVideoPlayer.removeFromSuperview()
        // Indicate that the video player has been removed.
        isVideoAdded = false
        cancellables.removeAll()
    }

I am just suing the prepareForReuse as per your suggestion and it is working great! but not too sure about how to implement the last 2 lines, should they be in the same prepareForReuse method?- ytVideoPlayer.removeEventListener(event:String, listener:String) // If already added any listeners
ytVideoPlayer.destroy()

Anyway, I am going to close this issue as I have already achieved sufficent performance :)
